### ISSUE TITLE
different mode merging?

### ISSUE THREAD

**Issue by yonderblue** [wadey/gocovmerge#2]
Why can't different modes be merged? I don't see any logic in the code to take any differences into account. When I look at the format in the files between count/atomic, it looks the same.

**Comment by wadey** [comment]
Is there a reason you would run into this issue in practice? It seems like if you want to merge the coverage outputs you would want to run them all with the same arguments.

Also, the current code actually only merges with the `set` style. A separate issue should be opened to merge the counts correctly if the other modes are detected (basically, undo [this patch](https://github.com/wadey/gocovmerge/commit/af8dc8edf8ee87c9add7aa0ed1941c88a52a0fea) if the mode is `count` or `atomic`)

**Comment by wadey** [comment]
I pushed a change to accumulate the "count" correctly for each `-covermode` type: https://github.com/wadey/gocovmerge/commit/b5bfa59ec0adc420475f97f89b58045c721d761c

**Comment by yonderblue** [comment]
That is an awesome answer, an answer to why the code didn't show a difference and a patch to make it with a feature to boot. Thanks!

**Comment by yonderblue** [comment]
BTW I am always using atomic because of the race detector, so this works great
